name: run matrix test with different go versions
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18]
    steps:
      - run: |
          echo "$HOME/bin" >> "$GITHUB_PATH"
          echo "$HOME/gopath/bin" >> "$GITHUB_PATH"
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: actions/checkout@v2
      - name: install
        run: |
          task install-tools && \
          task install
      - name: verify preconditions
        run: task verify
      - run: task test integration-test